### ISSUE TITLE
Tikfoutje en vraag over NL-Alert

### ISSUE THREAD

**Issue by JosWijman** [redmaner/MIUI10-XML-DUTCH#31]
Ik gebruik een Redmi Note 4 met de Nederlandstalige vertaling.
Als ik een foutmelding krijg van de Essent App, staat er in de tekst "sammenvatting" met dubbele "m" i.p.v. "samenvatting" met één "m". Geen groot probleem maar lijkt oplosbaar.

Dat nu in MIUI10 de optie voor NL-Alert (bij Instellingen-->Netwerk-->Meer) is verdwenen, hangt dat samen met de vertaling of zit dat dieper in de ROM voor de Redmi Note 4?

Succes en bedankt voor het maken en onderhouden van de vertaling.

**Comment by redmaner** [comment]
Dank voor je report.

Dat tikfoutje kunnen we oplossen, dat NL-alert weg is ligt echter niet aan de vertaling. Kan het zijn dat het anders heet (nood oproepen, emergency broadcast)?

**Comment by Cueie** [comment]
Opgelost

**Comment by JosWijman** [comment]
De hele optie voor nood berichten of Cell Broadcast e.d. is helemaal verdwenen. In eerste instantie was hij er niet toen ik mijn Redmi Note4x kocht maar begin van dit jaar is hij beschikbaar gekomen bij netwerk en dan de optie voor 'meer'. Daar was ik erg blij mee. Zeker toen ik begin juni het testbericht van de overheid kreeg.
Nu is de optie weer verdwenen.
Jammer en eigenlijk een gemis.

Maar bedankt voor het verhelpen van de tikfout.

Groetjes,

Jos Wijman, Valkenswaard
________________________________
